/** Modules available to every business type */
export const commonModules = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/app',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Business overview and KPIs',
    category: 'core',
  },
  {
    id: 'sales',
    title: 'Sales',
    icon: 'TrendingUp',
    route: '/app/sales',
    permission: 'invoices.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Sales pipeline and transactions',
    category: 'core',
  },
  {
    id: 'invoices',
    title: 'Invoices',
    icon: 'FileText',
    route: '/app/invoices',
    permission: 'invoices.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'GST invoicing and billing',
    category: 'core',
  },
  {
    id: 'inventory',
    title: 'Inventory',
    icon: 'Boxes',
    route: '/app/inventory',
    permission: 'products.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Stock and inventory levels',
    category: 'core',
  },
  {
    id: 'customers',
    title: 'Customers',
    icon: 'Users',
    route: '/app/customers',
    permission: 'customers.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Customer ledger',
    category: 'core',
  },
  {
    id: 'suppliers',
    title: 'Suppliers',
    icon: 'Truck',
    route: '/app/suppliers',
    permission: 'products.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Supplier directory',
    category: 'core',
  },
  {
    id: 'employees',
    title: 'Employees',
    icon: 'UserPlus',
    route: '/app/team',
    permission: 'members.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Team and employees',
    category: 'core',
  },
  {
    id: 'reports',
    title: 'Reports',
    icon: 'BarChart3',
    route: '/app/reports',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Operational reports',
    category: 'insights',
  },
  {
    id: 'analytics',
    title: 'Analytics',
    icon: 'TrendingUp',
    route: '/app/analytics',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'growth',
    description: 'Advanced analytics',
    category: 'insights',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    icon: 'Bell',
    route: '/app/notifications',
    permission: 'settings.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Notification center',
    category: 'core',
    sidebar: false,
  },
  {
    id: 'profile',
    title: 'Profile',
    icon: 'User',
    route: '/app/settings',
    permission: 'settings.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'User profile',
    category: 'core',
    sidebar: false,
  },
  {
    id: 'settings',
    title: 'Settings',
    icon: 'Settings',
    route: '/app/settings',
    permission: 'settings.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Business settings',
    category: 'core',
  },
  {
    id: 'search',
    title: 'Search',
    icon: 'Search',
    route: '/app/search',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Global search',
    category: 'core',
    sidebar: false,
  },
  {
    id: 'activity',
    title: 'Activity Timeline',
    icon: 'ScrollText',
    route: '/app/activity',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Recent activity and audit trail',
    category: 'core',
  },
  {
    id: 'quick-actions',
    title: 'Quick Actions',
    icon: 'Zap',
    route: '/app',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Shortcuts for common tasks',
    category: 'core',
    sidebar: false,
  },
  // Existing Biizora modules (preserved)
  {
    id: 'expenses',
    title: 'Expenses',
    icon: 'CreditCard',
    route: '/app/expenses',
    permission: 'expenses.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Expense tracking',
    category: 'finance',
  },
  {
    id: 'products',
    title: 'Products',
    icon: 'Package',
    route: '/app/products',
    permission: 'products.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Product catalogue',
    category: 'core',
  },
  {
    id: 'team',
    title: 'Team',
    icon: 'UserPlus',
    route: '/app/team',
    permission: 'members.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Team management',
    category: 'core',
    sidebar: false,
  },
  {
    id: 'billing',
    title: 'Billing',
    icon: 'Sliders',
    route: '/app/billing',
    permission: 'billing.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Subscription billing',
    category: 'admin',
    sidebar: false,
  },
  {
    id: 'membership',
    title: 'Membership',
    icon: 'BadgeCheck',
    route: '/app/membership',
    permission: 'billing.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Plan, subscription status, and renewals',
    category: 'admin',
  },
  {
    id: 'ai-suite',
    title: 'AI Suite',
    icon: 'Sparkles',
    route: '/app/ai-suite',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'growth',
    description: 'AI business copilots',
    category: 'ai',
  },
  {
    id: 'migration',
    title: 'Data Migration',
    icon: 'Database',
    route: '/app/migration',
    permission: 'settings.write',
    businessTypes: ['*'],
    requiredPlan: 'professional',
    description: 'Import and migrate data',
    category: 'admin',
  },
  {
    id: 'payments',
    title: 'Payments',
    icon: 'Zap',
    route: '/app/payments',
    permission: 'invoices.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Payment collection',
    category: 'finance',
  },
  {
    id: 'support',
    title: 'Support',
    icon: 'Headphones',
    route: '/app/support',
    permission: 'support.read',
    businessTypes: ['*'],
    requiredPlan: 'starter',
    description: 'Help and remote support',
    category: 'core',
  },
];
