/**
 * Feature-flag gated modules — only visible when Business.customFeatures includes the flag.
 */
export const customModules = [
  {
    id: 'vehicle-tracking',
    title: 'Vehicle Tracking',
    icon: 'Truck',
    route: '/app/vehicle-tracking',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'enterprise',
    requiredFeature: 'vehicleTracking',
    description: 'Fleet and delivery vehicle tracking',
    category: 'custom',
  },
  {
    id: 'repair-center',
    title: 'Repair Center',
    icon: 'Wrench',
    route: '/app/repair-center',
    permission: 'products.write',
    businessTypes: ['*'],
    requiredPlan: 'professional',
    requiredFeature: 'repairCenter',
    description: 'Repair job cards and workflows',
    category: 'custom',
  },
  {
    id: 'medicine-expiry',
    title: 'Medicine Expiry',
    icon: 'Pill',
    route: '/app/medicine-expiry',
    permission: 'products.read',
    businessTypes: ['*'],
    requiredPlan: 'professional',
    requiredFeature: 'medicineExpiry',
    description: 'Batch expiry monitoring',
    category: 'custom',
  },
  {
    id: 'purchase-approval',
    title: 'Purchase Approval',
    icon: 'CheckSquare',
    route: '/app/purchase-approval',
    permission: 'products.write',
    businessTypes: ['*'],
    requiredPlan: 'professional',
    requiredFeature: 'purchaseApproval',
    description: 'Purchase approval workflows',
    category: 'custom',
  },
  {
    id: 'ai-forecasting',
    title: 'AI Forecasting',
    icon: 'Sparkles',
    route: '/app/ai-forecasting',
    permission: 'reports.read',
    businessTypes: ['*'],
    requiredPlan: 'enterprise',
    requiredFeature: 'AIForecasting',
    description: 'AI demand and revenue forecasts',
    category: 'custom',
  },
  {
    id: 'ai-hair-recommendation',
    title: 'AI Hair Recommendation',
    icon: 'Sparkles',
    route: '/app/ai-hair',
    permission: 'customers.read',
    businessTypes: ['salon'],
    requiredPlan: 'enterprise',
    requiredFeature: 'AIHairRecommendation',
    description: 'AI hair look recommendations',
    category: 'custom',
  },
  {
    id: 'table-reservation-ai',
    title: 'Table Reservation AI',
    icon: 'Sparkles',
    route: '/app/reservation-ai',
    permission: 'customers.write',
    businessTypes: ['restaurant', 'cafe'],
    requiredPlan: 'enterprise',
    requiredFeature: 'TableReservationAI',
    description: 'AI-assisted reservations',
    category: 'custom',
  },
  {
    id: 'amazon-sync',
    title: 'Amazon Sync',
    icon: 'ShoppingCart',
    route: '/app/amazon-sync',
    permission: 'products.write',
    businessTypes: ['retail'],
    requiredPlan: 'enterprise',
    requiredFeature: 'AmazonSync',
    description: 'Amazon catalogue and order sync',
    category: 'custom',
  },
];
