/**
 * Biizora Manufacturing ERP Demo Data
 * Gujarat-based manufacturing suppliers, raw materials, production orders, machines, warehouses, and QC inspections.
 */

export const INITIAL_SUPPLIERS = [
  {
    id: 'SUP-001',
    name: 'Apex Metals & Alloys',
    company: 'Apex Metals & Alloys Pvt Ltd',
    gstin: '24AAACA1234A1Z5',
    pan: 'AAACA1234A',
    contactPerson: 'Rajesh Patel',
    phone: '+91 98250 11223',
    email: 'sales@apexmetals.in',
    address: 'Phase III, GIDC Vatva',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '382445',
    outstanding: 145000,
    status: 'Active',
    paymentTerms: 'Net 30',
    bankDetails: 'HDFC Bank - A/C 50200012345678 (HDFC0000123)',
    notes: 'Primary SS 304 and Aluminum ingot supplier with mill test certificates.'
  },
  {
    id: 'SUP-002',
    name: 'Gujarat Polymers Pvt Ltd',
    company: 'Gujarat Polymers Pvt Ltd',
    gstin: '24AABCG5678B1Z2',
    pan: 'AABCG5678B',
    contactPerson: 'Vikram Shah',
    phone: '+91 98980 44556',
    email: 'orders@gujaratpolymers.com',
    address: 'Plot 45, GIDC Makarpura',
    city: 'Vadodara',
    state: 'Gujarat',
    pincode: '390010',
    outstanding: 82500,
    status: 'Active',
    paymentTerms: 'Net 15',
    bankDetails: 'ICICI Bank - A/C 001205009876 (ICIC0000012)',
    notes: 'Polypropylene and Nylon virgin granule importer.'
  },
  {
    id: 'SUP-003',
    name: 'Mahavir Fasteners & Tools',
    company: 'Mahavir Fasteners & Tools',
    gstin: '24AACCM9012C1Z8',
    pan: 'AACCM9012C',
    contactPerson: 'Hitesh Chothani',
    phone: '+91 94262 77889',
    email: 'info@mahavirfasteners.co.in',
    address: '8-A National Highway, Metoda GIDC',
    city: 'Rajkot',
    state: 'Gujarat',
    pincode: '360021',
    outstanding: 0,
    status: 'Active',
    paymentTerms: 'Immediate',
    bankDetails: 'Axis Bank - A/C 91402001122334 (UTIB0000244)',
    notes: 'High tensile M8/M10/M12 bolts, nuts, and washers.'
  },
  {
    id: 'SUP-004',
    name: 'Surat Textile Auxiliaries',
    company: 'Surat Textile & Chemical Corp',
    gstin: '24AADCS3456D1Z1',
    pan: 'AADCS3456D',
    contactPerson: 'Paresh Vashi',
    phone: '+91 97277 33441',
    email: 'contact@suratchem.com',
    address: 'Udhna Magdalla Road, GIDC Udhna',
    city: 'Surat',
    state: 'Gujarat',
    pincode: '394210',
    outstanding: 310000,
    status: 'Outstanding Payment',
    paymentTerms: 'Net 45',
    bankDetails: 'State Bank of India - A/C 30112233445 (SBIN0001234)',
    notes: 'Industrial pigments and dyes. Overdue payment under review.'
  },
  {
    id: 'SUP-005',
    name: 'Saurashtra Castings',
    company: 'Saurashtra Industrial Castings Ltd',
    gstin: '24AAEFS7890E1Z4',
    pan: 'AAEFS7890E',
    contactPerson: 'Nilesh Patel',
    phone: '+91 99099 88112',
    email: 'nilesh@saurashtracastings.in',
    address: 'Lakhdhirpur Road',
    city: 'Morbi',
    state: 'Gujarat',
    pincode: '363642',
    outstanding: 65000,
    status: 'Active',
    paymentTerms: 'Net 30',
    bankDetails: 'Bank of Baroda - A/C 081201000123 (BARB0MORBII)',
    notes: 'Ductile iron and CI heavy castings.'
  },
  {
    id: 'SUP-006',
    name: 'Kadam Chemicals',
    company: 'Kadam Specialty Chemicals Pvt Ltd',
    gstin: '24AAAFK1122F1Z9',
    pan: 'AAAFK1122F',
    contactPerson: 'Dharmendra Rana',
    phone: '+91 98241 66778',
    email: 'dharmendra@kadamchem.com',
    address: 'GIDC Industrial Estate',
    city: 'Ankleshwar',
    state: 'Gujarat',
    pincode: '393002',
    outstanding: 215000,
    status: 'Outstanding Payment',
    paymentTerms: 'Net 30',
    bankDetails: 'Kotak Mahindra - A/C 4511223344 (KKBK0000881)',
    notes: 'Solvent C9 and specialty degreasers.'
  },
  {
    id: 'SUP-007',
    name: 'Ambica Packaging Industries',
    company: 'Ambica Packaging Industries',
    gstin: '24AABCA4455G1Z3',
    pan: 'AABCA4455G',
    contactPerson: 'Sanjay Mehta',
    phone: '+91 98981 22334',
    email: 'sanjay@ambicapack.in',
    address: 'Chhatral GIDC',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '382729',
    outstanding: 18000,
    status: 'Active',
    paymentTerms: 'Net 15',
    bankDetails: 'HDFC Bank - A/C 50200088776655 (HDFC0000451)',
    notes: 'Corrugated 3-ply and 5-ply export packaging boxes.'
  },
  {
    id: 'SUP-008',
    name: 'Navrang Rubber Moulding',
    company: 'Navrang Polymer & Rubber Works',
    gstin: '24AACCN7788H1Z6',
    pan: 'AACCN7788H',
    contactPerson: 'Kirit Desai',
    phone: '+91 94271 55667',
    email: 'navrang@vapurubber.com',
    address: 'GIDC Phase II',
    city: 'Vapi',
    state: 'Gujarat',
    pincode: '396195',
    outstanding: 0,
    status: 'Inactive',
    paymentTerms: 'Immediate',
    bankDetails: 'Union Bank of India - A/C 123456789012 (UBIN0530123)',
    notes: 'Custom EPDM and Viton rubber O-rings.'
  }
];

export const INITIAL_RAW_MATERIALS = [
  {
    id: 'RM-001',
    code: 'RM-SS-304',
    name: 'SS 304 Sheets 2mm',
    category: 'Metals',
    unit: 'Kg',
    stock: 1450,
    reorderLevel: 500,
    unitCost: 220,
    supplier: 'Apex Metals & Alloys',
    location: 'Rack A-12',
    hsnCode: '7219',
    description: 'Cold rolled stainless steel 304 grade sheets'
  },
  {
    id: 'RM-002',
    code: 'RM-PP-GRN',
    name: 'Polypropylene Granules',
    category: 'Polymers',
    unit: 'Kg',
    stock: 280,
    reorderLevel: 600,
    unitCost: 110,
    supplier: 'Gujarat Polymers Pvt Ltd',
    location: 'Silo B-04',
    hsnCode: '3902',
    description: 'Injection grade virgin PP granules'
  },
  {
    id: 'RM-003',
    code: 'RM-FST-M10',
    name: 'M10 Hex Bolt 50mm',
    category: 'Fasteners',
    unit: 'Piece',
    stock: 12500,
    reorderLevel: 3000,
    unitCost: 4.5,
    supplier: 'Mahavir Fasteners & Tools',
    location: 'Bin C-10',
    hsnCode: '7318',
    description: 'Grade 8.8 high tensile zinc plated hex bolt'
  },
  {
    id: 'RM-004',
    code: 'RM-CHM-BLU',
    name: 'Industrial Dyes - Pigment Blue',
    category: 'Chemicals',
    unit: 'Liter',
    stock: 45,
    reorderLevel: 100,
    unitCost: 850,
    supplier: 'Kadam Chemicals',
    location: 'HazMat Room H-01',
    hsnCode: '3204',
    description: 'Concentrated phthalocyanine blue solvent dye'
  },
  {
    id: 'RM-005',
    code: 'RM-AL-ING',
    name: 'Aluminum Ingot Grade A',
    category: 'Metals',
    unit: 'Kg',
    stock: 3200,
    reorderLevel: 1000,
    unitCost: 195,
    supplier: 'Saurashtra Castings',
    location: 'Yard A-01',
    hsnCode: '7601',
    description: '99.7% pure primary aluminum foundry ingots'
  },
  {
    id: 'RM-006',
    code: 'RM-PKG-BX3',
    name: 'Corrugated Packaging Boxes 3-Ply',
    category: 'Packaging',
    unit: 'Box',
    stock: 450,
    reorderLevel: 800,
    unitCost: 28,
    supplier: 'Ambica Packaging Industries',
    location: 'Store P-02',
    hsnCode: '4819',
    description: 'Kraft paper 150 GSM outer corrugated box'
  },
  {
    id: 'RM-007',
    code: 'RM-RBR-GSK',
    name: 'EPDM Rubber Gaskets 50mm',
    category: 'Rubber',
    unit: 'Piece',
    stock: 1800,
    reorderLevel: 500,
    unitCost: 15,
    supplier: 'Navrang Rubber Moulding',
    location: 'Bin R-05',
    hsnCode: '4016',
    description: 'High temperature oil-resistant EPDM gasket'
  },
  {
    id: 'RM-008',
    code: 'RM-MS-FLT',
    name: 'MS Flat Bar 50x6mm',
    category: 'Metals',
    unit: 'Meter',
    stock: 850,
    reorderLevel: 300,
    unitCost: 160,
    supplier: 'Apex Metals & Alloys',
    location: 'Rack A-05',
    hsnCode: '7211',
    description: 'Mild steel commercial structural flat bar'
  },
  {
    id: 'RM-009',
    code: 'RM-CHM-SOL',
    name: 'Industrial Solvent C9',
    category: 'Chemicals',
    unit: 'Liter',
    stock: 600,
    reorderLevel: 250,
    unitCost: 140,
    supplier: 'Kadam Chemicals',
    location: 'Drum Storage D-03',
    hsnCode: '2707',
    description: 'Aromatic solvent C9 grade for degreasing'
  },
  {
    id: 'RM-010',
    code: 'RM-PL-NYL',
    name: 'Nylon Rod 40mm Dia',
    category: 'Polymers',
    unit: 'Meter',
    stock: 95,
    reorderLevel: 150,
    unitCost: 420,
    supplier: 'Gujarat Polymers Pvt Ltd',
    location: 'Rack P-11',
    hsnCode: '3916',
    description: 'Extruded Nylon 6 cast rod for CNC machining'
  }
];

export const INITIAL_PRODUCTION_ORDERS = [
  {
    id: 'PO-2026-089',
    productName: 'Heavy Duty Valve Body Assembly',
    productSku: 'PRD-VLV-01',
    batchNo: 'BATCH-8801',
    quantity: 500,
    unit: 'Piece',
    startDate: '2026-08-01',
    dueDate: '2026-08-15',
    machine: '5-Axis CNC Milling Station (MC-01)',
    supervisor: 'Ramesh Bhai',
    progress: 75,
    status: 'In Progress',
    priority: 'High',
    notes: 'Export order for Middle East client. Hydrostatic test required.'
  },
  {
    id: 'PO-2026-090',
    productName: 'Hydraulic Cylinder Casing',
    productSku: 'PRD-HYD-04',
    batchNo: 'BATCH-8802',
    quantity: 250,
    unit: 'Piece',
    startDate: '2026-08-05',
    dueDate: '2026-08-20',
    machine: 'Heavy Duty Turning Lathe (L-03)',
    supervisor: 'Vijay Kumar',
    progress: 30,
    status: 'In Progress',
    priority: 'Medium',
    notes: 'Internal honing tolerance strictly +/- 0.02mm.'
  },
  {
    id: 'PO-2026-091',
    productName: 'Plastic Electrical Enclosure',
    productSku: 'PRD-ENC-02',
    batchNo: 'BATCH-8803',
    quantity: 2000,
    unit: 'Piece',
    startDate: '2026-08-10',
    dueDate: '2026-08-18',
    machine: '350T Injection Moulding (IM-02)',
    supervisor: 'Paresh Patel',
    progress: 0,
    status: 'Planned',
    priority: 'Normal',
    notes: 'Awaiting completion of mould temperature calibration.'
  },
  {
    id: 'PO-2026-088',
    productName: 'Precision Aluminum Heat Sink',
    productSku: 'PRD-HSK-09',
    batchNo: 'BATCH-8798',
    quantity: 1200,
    unit: 'Piece',
    startDate: '2026-07-25',
    dueDate: '2026-08-08',
    machine: 'Fiber Laser Cutter 6kW (LC-01)',
    supervisor: 'Ramesh Bhai',
    progress: 100,
    status: 'Completed',
    priority: 'Urgent',
    notes: 'QC passed 100%. Transferred to finished goods store.'
  },
  {
    id: 'PO-2026-092',
    productName: 'Custom Conveyor Roller Assembly',
    productSku: 'PRD-CNV-07',
    batchNo: 'BATCH-8804',
    quantity: 150,
    unit: 'Piece',
    startDate: '2026-08-12',
    dueDate: '2026-08-25',
    machine: 'Automated Assembly Line (AC-01)',
    supervisor: 'Nitin Shah',
    progress: 15,
    status: 'On Hold',
    priority: 'High',
    notes: 'Paused for bearing supplier delivery verification.'
  }
];

export const INITIAL_MACHINES = [
  {
    id: 'MC-01',
    name: '5-Axis CNC Milling Station',
    type: 'CNC Mill',
    department: 'Machining',
    capacity: '120 Pcs/hr',
    status: 'Running',
    lastMaintenance: '2026-07-15',
    nextMaintenance: '2026-08-25',
    utilization: 92,
    operator: 'Mahendra Singh',
    serialNo: 'CNC-5X-2023-901',
    purchaseDate: '2023-04-12',
    warrantyExpiry: '2026-04-12',
    operatingHours: 4280,
    currentOrder: 'PO-2026-089'
  },
  {
    id: 'LC-01',
    name: 'Fiber Laser Cutter 6kW',
    type: 'Laser Cutting',
    department: 'Sheet Metal',
    capacity: '350 Sheets/hr',
    status: 'Running',
    lastMaintenance: '2026-08-01',
    nextMaintenance: '2026-09-01',
    utilization: 88,
    operator: 'Rajesh Solanki',
    serialNo: 'FLC-6000-2024-11',
    purchaseDate: '2024-01-18',
    warrantyExpiry: '2027-01-18',
    operatingHours: 2150,
    currentOrder: 'PO-2026-088'
  },
  {
    id: 'IM-02',
    name: '350 Ton Injection Moulding Press',
    type: 'Injection Moulding',
    department: 'Plastics',
    capacity: '450 Pcs/hr',
    status: 'Maintenance',
    lastMaintenance: '2026-08-10',
    nextMaintenance: '2026-08-14',
    utilization: 45,
    operator: 'Amit Trivedi',
    serialNo: 'IMP-350-2022-44',
    purchaseDate: '2022-09-05',
    warrantyExpiry: '2025-09-05',
    operatingHours: 8900,
    currentOrder: 'PO-2026-091'
  },
  {
    id: 'L-03',
    name: 'Heavy Duty Turning Lathe',
    type: 'Lathe',
    department: 'Machining',
    capacity: '40 Pcs/hr',
    status: 'Running',
    lastMaintenance: '2026-06-20',
    nextMaintenance: '2026-08-20',
    utilization: 78,
    operator: 'Sunil Parmar',
    serialNo: 'HDL-2021-008',
    purchaseDate: '2021-11-30',
    warrantyExpiry: '2024-11-30',
    operatingHours: 11200,
    currentOrder: 'PO-2026-090'
  },
  {
    id: 'AC-01',
    name: 'Automated Assembly & Testing Line',
    type: 'Assembly Conveyor',
    department: 'Final Assembly',
    capacity: '200 Pcs/hr',
    status: 'Idle',
    lastMaintenance: '2026-07-28',
    nextMaintenance: '2026-08-28',
    utilization: 60,
    operator: 'Pravin Koli',
    serialNo: 'AAL-2023-552',
    purchaseDate: '2023-08-15',
    warrantyExpiry: '2026-08-15',
    operatingHours: 3400,
    currentOrder: 'PO-2026-092'
  },
  {
    id: 'PB-01',
    name: 'Hydraulic Press Brake 200T',
    type: 'Bending',
    department: 'Sheet Metal',
    capacity: '180 Bends/hr',
    status: 'Breakdown',
    lastMaintenance: '2026-07-05',
    nextMaintenance: '2026-08-11',
    utilization: 10,
    operator: 'Jignesh Patel',
    serialNo: 'HPB-200-2020-03',
    purchaseDate: '2020-03-22',
    warrantyExpiry: '2023-03-22',
    operatingHours: 14500,
    currentOrder: 'None'
  }
];

export const INITIAL_WAREHOUSES = [
  {
    id: 'WH-A',
    name: 'Main Central Warehouse',
    code: 'WH-A',
    type: 'Raw Materials & Finished Goods',
    location: 'Building 1 - Vatva',
    capacity: '85%',
    totalItems: 420,
    reservedStock: 45,
    supervisor: 'Manish Trivedi'
  },
  {
    id: 'WH-B',
    name: 'Raw Material Store',
    code: 'WH-B',
    type: 'Raw Materials',
    location: 'Building 2 - Vatva',
    capacity: '72%',
    totalItems: 180,
    reservedStock: 28,
    supervisor: 'Karan Patel'
  },
  {
    id: 'WH-C',
    name: 'Finished Goods Warehouse',
    code: 'WH-C',
    type: 'Finished Goods',
    location: 'Building 3 - Vatva',
    capacity: '90%',
    totalItems: 210,
    reservedStock: 65,
    supervisor: 'Sanjay Joshi'
  },
  {
    id: 'WH-D',
    name: 'Dispatch & Staging Area',
    code: 'WH-D',
    type: 'Transit',
    location: 'Dock 4 & 5',
    capacity: '40%',
    totalItems: 55,
    reservedStock: 50,
    supervisor: 'Rakesh Verma'
  }
];

export const INITIAL_WAREHOUSE_ITEMS = [
  {
    id: 'WI-001',
    sku: 'RM-SS-304',
    itemName: 'SS 304 Sheets 2mm',
    warehouse: 'Main Central Warehouse (WH-A)',
    rackBin: 'Rack A-12 / Bin 04',
    availableQty: 1200,
    reservedQty: 250,
    damagedQty: 0,
    unit: 'Kg',
    lastMovement: '2026-08-11 14:30'
  },
  {
    id: 'WI-002',
    sku: 'PRD-VLV-01',
    itemName: 'Heavy Duty Valve Body Assembly',
    warehouse: 'Finished Goods Warehouse (WH-C)',
    rackBin: 'Rack FG-01 / Shelf B',
    availableQty: 375,
    reservedQty: 100,
    damagedQty: 2,
    unit: 'Piece',
    lastMovement: '2026-08-11 11:15'
  },
  {
    id: 'WI-003',
    sku: 'RM-PP-GRN',
    itemName: 'Polypropylene Granules',
    warehouse: 'Raw Material Store (WH-B)',
    rackBin: 'Silo B-04',
    availableQty: 200,
    reservedQty: 80,
    damagedQty: 0,
    unit: 'Kg',
    lastMovement: '2026-08-10 16:45'
  },
  {
    id: 'WI-004',
    sku: 'PRD-HSK-09',
    itemName: 'Precision Aluminum Heat Sink',
    warehouse: 'Dispatch & Staging Area (WH-D)',
    rackBin: 'Dock 4 Staging',
    availableQty: 1200,
    reservedQty: 1200,
    damagedQty: 0,
    unit: 'Piece',
    lastMovement: '2026-08-11 09:00'
  },
  {
    id: 'WI-005',
    sku: 'RM-AL-ING',
    itemName: 'Aluminum Ingot Grade A',
    warehouse: 'Main Central Warehouse (WH-A)',
    rackBin: 'Yard A-01 / Pallet 12',
    availableQty: 2800,
    reservedQty: 400,
    damagedQty: 0,
    unit: 'Kg',
    lastMovement: '2026-08-09 10:20'
  }
];

export const INITIAL_QC_INSPECTIONS = [
  {
    id: 'QC-2026-101',
    batchNo: 'BATCH-8801',
    productionOrder: 'PO-2026-089',
    productName: 'Heavy Duty Valve Body Assembly',
    inspector: 'Jayesh Parmar',
    inspectionDate: '2026-08-11',
    inspectionType: 'Final Inspection',
    parameter: 'Dimensional Accuracy & Pressure Test 50 Bar',
    expectedValue: '50 Bar / Zero Leakage',
    actualValue: '50 Bar / Passed',
    tolerance: '+/- 0.01mm',
    result: 'Pass',
    status: 'Passed',
    remarks: 'Complies with ASME B16.34 standards. Pressure held for 15 mins.',
    defectCategory: 'None'
  },
  {
    id: 'QC-2026-102',
    batchNo: 'BATCH-8802',
    productionOrder: 'PO-2026-088',
    productName: 'Precision Aluminum Heat Sink',
    inspector: 'Shraddha Bhatt',
    inspectionDate: '2026-08-11',
    inspectionType: 'In-Process QC',
    parameter: 'Surface Roughness Ra <= 0.8um',
    expectedValue: '0.8 um',
    actualValue: '0.65 um',
    tolerance: '+/- 0.1um',
    result: 'Pass',
    status: 'Passed',
    remarks: 'Anodizing coating thickness uniform at 22 microns.',
    defectCategory: 'None'
  },
  {
    id: 'QC-2026-103',
    batchNo: 'BATCH-8799',
    productionOrder: 'PO-2026-090',
    productName: 'Hydraulic Cylinder Casing',
    inspector: 'Jayesh Parmar',
    inspectionDate: '2026-08-10',
    inspectionType: 'Bore Gauge Audit',
    parameter: 'Inner Bore Diameter Tolerance +-0.02mm',
    expectedValue: '80.00 mm',
    actualValue: '80.05 mm',
    tolerance: '+/- 0.02mm',
    result: 'Fail',
    status: 'Rework Required',
    remarks: 'Bore oversized by 0.03mm. Sent back to lathe station L-03 for re-honing.',
    defectCategory: 'Dimensional Deviation'
  },
  {
    id: 'QC-2026-104',
    batchNo: 'BATCH-8795',
    productionOrder: 'PO-2026-091',
    productName: 'Plastic Electrical Enclosure',
    inspector: 'Shraddha Bhatt',
    inspectionDate: '2026-08-10',
    inspectionType: 'Material & Mold Test',
    parameter: 'Wall Thickness & Tensile Strength',
    expectedValue: '3.0 mm',
    actualValue: '3.02 mm',
    tolerance: '+/- 0.1mm',
    result: 'Pass',
    status: 'Passed',
    remarks: 'Flame retardancy UL94 V-0 verified.',
    defectCategory: 'None'
  },
  {
    id: 'QC-2026-105',
    batchNo: 'BATCH-8790',
    productionOrder: 'PO-2026-085',
    productName: 'M10 Hex Bolt Lots',
    inspector: 'Chirag Vora',
    inspectionDate: '2026-08-09',
    inspectionType: 'Receiving Inspection',
    parameter: 'Thread Pitch & Zinc Plating Micron',
    expectedValue: '12 Microns',
    actualValue: '5 Microns',
    tolerance: 'Min 10 Microns',
    result: 'Fail',
    status: 'Failed',
    remarks: 'Plating thickness failed salt spray test. Rejected lot back to vendor.',
    defectCategory: 'Coating / Plating Defect'
  },
  {
    id: 'QC-2026-106',
    batchNo: 'BATCH-8788',
    productionOrder: 'PO-2026-084',
    productName: 'SS 304 Sheet Lots',
    inspector: 'Chirag Vora',
    inspectionDate: '2026-08-09',
    inspectionType: 'Raw Material Chemical Test',
    parameter: 'Spectro Chemical Analysis (Ni/Cr %)',
    expectedValue: 'Ni 8.0%, Cr 18.0%',
    actualValue: 'Ni 8.2%, Cr 18.1%',
    tolerance: 'ASTM A240',
    result: 'Pass',
    status: 'Passed',
    remarks: 'Chemical mill certificate validated with handheld XRF spectro.',
    defectCategory: 'None'
  },
  {
    id: 'QC-2026-107',
    batchNo: 'BATCH-8782',
    productionOrder: 'PO-2026-082',
    productName: 'Conveyor Roller Shaft',
    inspector: 'Jayesh Parmar',
    inspectionDate: '2026-08-08',
    inspectionType: 'Hardness & Runout',
    parameter: 'Concentricity & Hardness HRC 45',
    expectedValue: 'HRC 45-50',
    actualValue: 'HRC 38',
    tolerance: 'Min 45 HRC',
    result: 'Fail',
    status: 'Rework Required',
    remarks: 'Induction hardening temperature was low. Requires re-heat treatment.',
    defectCategory: 'Hardness Deficiency'
  },
  {
    id: 'QC-2026-108',
    batchNo: 'BATCH-8779',
    productionOrder: 'PO-2026-080',
    productName: 'EPDM Gaskets 50mm',
    inspector: 'Shraddha Bhatt',
    inspectionDate: '2026-08-07',
    inspectionType: 'Elongation & Shore Test',
    parameter: 'Shore Hardness 70A & Leakage Test',
    expectedValue: '70 A',
    actualValue: '71 A',
    tolerance: '+/- 5A',
    result: 'Pass',
    status: 'Passed',
    remarks: 'Satisfactory compression set test after 24 hrs.',
    defectCategory: 'None'
  }
];
