import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import { connectDB } from '../config/db.js';
import { User } from '../models/User.js';
import { Business } from '../models/Business.js';
import { Membership } from '../models/Membership.js';
import { Customer } from '../models/Customer.js';
import { Product } from '../models/Product.js';
import { Invoice } from '../models/Invoice.js';
import { Expense } from '../models/Expense.js';
import { Notification } from '../models/Notification.js';
import { ActivityLog } from '../models/ActivityLog.js';
import { getPermissionsForRole } from '../services/permissionDefaults.js';

dotenv.config();

async function seed() {
  await connectDB();

  await Promise.all([
    User.deleteMany({}),
    Business.deleteMany({}),
    Membership.deleteMany({}),
    Customer.deleteMany({}),
    Product.deleteMany({}),
    Invoice.deleteMany({}),
    Expense.deleteMany({}),
    Notification.deleteMany({}),
    ActivityLog.deleteMany({}),
  ]);

  const passwordHash = await bcrypt.hash('demo1234', 12);
  const user = await User.create({
    name: 'Adrian Hale',
    email: 'adrian.hale@biizora.demo',
    passwordHash,
    phone: '+91 98765 43210',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Adrian%20Hale',
    subscriptionPlan: 'Pro Plan',
    subscriptionStatus: 'active',
    trialDaysLeft: 14,
    preferences: { theme: 'light', timezone: 'Asia/Kolkata', language: 'en', bgStyle: 'mono-light' },
  });

  const business = await Business.create({
    name: 'Hale Analytics Group',
    tradeName: 'Hale Analytics',
    industry: 'Software & SaaS',
    gstin: '29ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    email: 'adrian.hale@biizora.demo',
    phone: '+91 98765 43210',
    website: 'https://biizora.in',
    logoUrl: '',
    address: {
      line1: 'Suite 402, Innovate Tech Park, Koramangala',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560095',
      country: 'India',
    },
    bankDetails: {
      bankName: 'HDFC Bank Ltd',
      accountName: 'Hale Analytics Group',
      accountNumber: '50200012345678',
      ifscCode: 'HDFC0001234',
      branch: 'Koramangala 4th Block',
      upiId: 'hale@hdfcbank',
    },
    taxSettings: {
      currency: 'INR',
      currencySymbol: '₹',
      defaultTaxRate: 18,
      invoicePrefix: 'INV-2026-',
      invoiceTheme: 'modern',
    },
    branding: { brandColor: '#171717', invoiceTheme: 'modern' },
    onboardingCompleted: true,
    createdBy: user._id,
  });

  const retail = await Business.create({
    name: 'Apex Retail Outlet',
    tradeName: 'Apex Retail',
    industry: 'Retail',
    email: 'adrian.hale@biizora.demo',
    createdBy: user._id,
    onboardingCompleted: true,
    taxSettings: {
      currency: 'INR',
      currencySymbol: '₹',
      defaultTaxRate: 18,
      invoicePrefix: 'AR-',
      invoiceTheme: 'modern',
    },
  });

  await Membership.create({
    userId: user._id,
    businessId: business._id,
    role: 'Owner',
    permissions: getPermissionsForRole('Owner'),
    status: 'active',
  });

  await Membership.create({
    userId: user._id,
    businessId: retail._id,
    role: 'Owner',
    permissions: getPermissionsForRole('Owner'),
    status: 'active',
  });

  const customers = await Customer.insertMany([
    {
      businessId: business._id,
      name: 'Apex Global Solutions',
      contactPerson: 'Rahul Verma',
      email: 'rahul@apexglobal.com',
      phone: '+91 98111 22334',
      gstin: '27AAACA1234A1Z1',
      pan: 'AAACA1234A',
      address: 'Plot 42, Bandra Kurla Complex',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      isIgst: true,
      outstandingBalance: 45000,
      totalSpent: 380000,
      status: 'active',
      category: 'Enterprise',
      notes: 'Key enterprise client. NET 30 payment terms.',
    },
    {
      businessId: business._id,
      name: 'Zenith Digital Media',
      contactPerson: 'Priya Sharma',
      email: 'priya@zenithdigital.in',
      phone: '+91 98222 33445',
      gstin: '29BBBCB5678B1Z2',
      pan: 'BBBCB5678B',
      address: '88, MG Road, Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560038',
      isIgst: false,
      outstandingBalance: 0,
      totalSpent: 195000,
      status: 'active',
      category: 'Agency',
      notes: 'Monthly retainer for UI/UX consulting.',
    },
    {
      businessId: business._id,
      name: 'Nova Retail & Logistics',
      contactPerson: 'Vikram Malhotra',
      email: 'accounts@novaretail.co.in',
      phone: '+91 98333 44556',
      gstin: '36CCCCD9012C1Z3',
      pan: 'CCCCD9012C',
      address: 'Hitec City Phase II',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      isIgst: true,
      outstandingBalance: 112000,
      totalSpent: 540000,
      status: 'active',
      category: 'Retailer',
      notes: 'Overdue payments pending.',
    },
    {
      businessId: business._id,
      name: 'Kaveri Engineering Works',
      contactPerson: 'Srinivas Rao',
      email: 'srinivas@kaverieng.com',
      phone: '+91 98444 55667',
      gstin: '33DDDDE3456D1Z4',
      pan: 'DDDDE3456D',
      address: 'Industrial Estate, Guindy',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600032',
      isIgst: true,
      outstandingBalance: 18500,
      totalSpent: 92000,
      status: 'active',
      category: 'Manufacturer',
      notes: 'Supplies custom hardware components.',
    },
  ]);

  const products = await Product.insertMany([
    {
      businessId: business._id,
      name: 'SaaS Software Subscription (Annual)',
      type: 'service',
      sku: 'BIZ-SAAS-ANN',
      hsnSac: '998314',
      category: 'Software',
      sellingPrice: 49999,
      costPrice: 12000,
      gstRate: 18,
      stock: 999,
      minStockLevel: 10,
      unit: 'license',
      description: 'Cloud ERP & Invoice Management License for 1 Year.',
    },
    {
      businessId: business._id,
      name: 'AI Automation Consulting',
      type: 'service',
      sku: 'BIZ-CONS-AI',
      hsnSac: '998313',
      category: 'Services',
      sellingPrice: 75000,
      costPrice: 25000,
      gstRate: 18,
      stock: 100,
      minStockLevel: 5,
      unit: 'project',
      description: 'Custom AI Workflow & Integration Implementation.',
    },
    {
      businessId: business._id,
      name: 'POS Smart Terminal X1',
      type: 'product',
      sku: 'BIZ-HW-POS1',
      hsnSac: '847130',
      category: 'Hardware',
      sellingPrice: 16500,
      costPrice: 11000,
      gstRate: 18,
      stock: 14,
      minStockLevel: 15,
      unit: 'unit',
      description: 'Touchscreen Android POS Machine with Thermal Printer.',
    },
    {
      businessId: business._id,
      name: 'Thermal Receipt Roll (Box of 50)',
      type: 'product',
      sku: 'BIZ-ACC-ROLL50',
      hsnSac: '481190',
      category: 'Supplies',
      sellingPrice: 1250,
      costPrice: 750,
      gstRate: 12,
      stock: 4,
      minStockLevel: 10,
      unit: 'box',
      description: 'High sensitivity 80mm thermal paper rolls.',
    },
  ]);

  await Invoice.insertMany([
    {
      businessId: business._id,
      invoiceNumber: 'INV-2026-001',
      customerId: customers[0]._id,
      customerName: customers[0].name,
      customerGstin: customers[0].gstin,
      issueDate: '2026-07-15',
      dueDate: '2026-08-14',
      items: [
        {
          description: products[0].name,
          hsnSac: '998314',
          quantity: 2,
          rate: 49999,
          gstRate: 18,
          amount: 99998,
          taxAmount: 17999.64,
        },
      ],
      subtotal: 99998,
      discount: 5000,
      taxableAmount: 94998,
      cgst: 0,
      sgst: 0,
      igst: 17099.64,
      totalTax: 17099.64,
      shippingCharge: 0,
      grandTotal: 112097.64,
      status: 'paid',
      paidAmount: 112097.64,
      paymentMethod: 'Razorpay / UPI',
      notes: 'Payment received in full.',
      terms: 'Goods once sold are non-refundable.',
    },
    {
      businessId: business._id,
      invoiceNumber: 'INV-2026-002',
      customerId: customers[1]._id,
      customerName: customers[1].name,
      customerGstin: customers[1].gstin,
      issueDate: '2026-07-20',
      dueDate: '2026-08-04',
      items: [
        {
          description: products[1].name,
          hsnSac: '998313',
          quantity: 1,
          rate: 75000,
          gstRate: 18,
          amount: 75000,
          taxAmount: 13500,
        },
      ],
      subtotal: 75000,
      discount: 0,
      taxableAmount: 75000,
      cgst: 6750,
      sgst: 6750,
      igst: 0,
      totalTax: 13500,
      shippingCharge: 0,
      grandTotal: 88500,
      status: 'paid',
      paidAmount: 88500,
      paymentMethod: 'Bank Transfer (NEFT)',
      notes: 'Quarterly retainer payment.',
      terms: 'Payment terms 15 days.',
    },
    {
      businessId: business._id,
      invoiceNumber: 'INV-2026-003',
      customerId: customers[2]._id,
      customerName: customers[2].name,
      customerGstin: customers[2].gstin,
      issueDate: '2026-07-01',
      dueDate: '2026-07-16',
      items: [
        {
          description: products[2].name,
          hsnSac: '847130',
          quantity: 5,
          rate: 16500,
          gstRate: 18,
          amount: 82500,
          taxAmount: 14850,
        },
      ],
      subtotal: 82500,
      discount: 2500,
      taxableAmount: 80000,
      cgst: 0,
      sgst: 0,
      igst: 14400,
      totalTax: 14400,
      shippingCharge: 500,
      grandTotal: 94900,
      status: 'overdue',
      paidAmount: 0,
      paymentMethod: 'Pending',
      notes: 'Urgent: Payment overdue.',
      terms: '18% p.a. interest charged on delayed payments.',
    },
    {
      businessId: business._id,
      invoiceNumber: 'INV-2026-004',
      customerId: customers[3]._id,
      customerName: customers[3].name,
      customerGstin: customers[3].gstin,
      issueDate: '2026-07-28',
      dueDate: '2026-08-12',
      items: [
        {
          description: products[3].name,
          hsnSac: '481190',
          quantity: 10,
          rate: 1250,
          gstRate: 12,
          amount: 12500,
          taxAmount: 1500,
        },
      ],
      subtotal: 12500,
      discount: 0,
      taxableAmount: 12500,
      cgst: 0,
      sgst: 0,
      igst: 1500,
      totalTax: 1500,
      shippingCharge: 350,
      grandTotal: 14350,
      status: 'pending',
      paidAmount: 0,
      paymentMethod: 'UPI / QR',
      notes: 'Delivered via BlueDart Express.',
      terms: 'NET 15 payment terms.',
    },
  ]);

  await Expense.insertMany([
    {
      businessId: business._id,
      title: 'AWS & Cloud Server Hosting',
      category: 'Office & Tech',
      amount: 24500,
      date: '2026-07-05',
      paymentMode: 'Corporate Card',
      vendor: 'Amazon Web Services',
      gstClaimable: true,
      gstAmount: 3737,
      status: 'paid',
      notes: 'Monthly production compute clusters.',
    },
    {
      businessId: business._id,
      title: 'Koramangala Office Rent',
      category: 'Rent',
      amount: 65000,
      date: '2026-07-01',
      paymentMode: 'Bank Transfer',
      vendor: 'Innovate Park Developers',
      gstClaimable: true,
      gstAmount: 9915,
      status: 'paid',
      notes: 'Monthly office lease.',
    },
    {
      businessId: business._id,
      title: 'Google Workspace & Software Tools',
      category: 'Office & Tech',
      amount: 12800,
      date: '2026-07-10',
      paymentMode: 'Corporate Card',
      vendor: 'Google India',
      gstClaimable: true,
      gstAmount: 1952,
      status: 'paid',
      notes: '25 Workspace accounts.',
    },
    {
      businessId: business._id,
      title: 'Team Performance Bonus & Stipends',
      category: 'Salary',
      amount: 145000,
      date: '2026-07-31',
      paymentMode: 'Bank Transfer',
      vendor: 'Internal Payroll',
      gstClaimable: false,
      gstAmount: 0,
      status: 'paid',
      notes: 'July payroll disbursement.',
    },
    {
      businessId: business._id,
      title: 'Digital Marketing & LinkedIn Ads',
      category: 'Marketing',
      amount: 32000,
      date: '2026-07-22',
      paymentMode: 'Corporate Card',
      vendor: 'LinkedIn Ireland',
      gstClaimable: true,
      gstAmount: 4881,
      status: 'paid',
      notes: 'B2B SaaS lead acquisition campaign.',
    },
  ]);

  await Notification.create({
    businessId: business._id,
    userId: user._id,
    title: 'Welcome to Biizora',
    message: 'Your AI-powered business operating system is ready. Explore invoices, team, and settings.',
    type: 'system',
  });

  await ActivityLog.create({
    businessId: business._id,
    userId: user._id,
    userName: user.name,
    action: 'system.seeded',
    entityType: 'Business',
    entityId: business._id.toString(),
    details: 'Demo workspace seeded',
  });

  console.log('✓ Biizora seed complete');
  console.log('  Email:    adrian.hale@biizora.demo');
  console.log('  Password: demo1234');
  console.log(`  Business: ${business.name} (${business._id})`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
